replicaCount: 3

image:
  repository : tiligan/flasksqlite
  pullPolicy : IfNotPresent
  tag        : "latest"

service:
  enable     : true
  name       : my-flask-service
  type       : ClusterIP
  port       : 80
  targetPort : 5000
  portName   : http

resources: 
  limits:
    cpu    : 200m
    memory : 128Mi
  requests:
    cpu    : 200m
    memory : 128Mi

autoscaling:
  enabled                           : false
  minReplicas                       : 1
  maxReplicas                       : 4
  targetCPUUtilizationPercentage    : 80
  targetMemoryUtilizationPercentage : 80

serviceAccount:
  create: true